### ISSUE TITLE
Runtime exception: wavm.reachedUnreachable

### ISSUE THREAD

**Issue by SheronLv** [WAVM/WAVM#118]
I wrote a C file named f.c, and used emcc  transferring f.c to f.wasm,  then I used wavm-disas transferring f.wasm to f.wast.   Finally , I run 'wavm-run  f.wast',  the runtime exception occurs.

1. 
my f.c file like this:
`
#include "time.h"
#include "stdio.h"

int math(int x) {
    double result = 0;
    for(int i = 0; i < 1000000000; ++i){
        result = x * x;
    }
    return result;
}

int main() {
    const clock_t begin_time = clock();
    math(2);
    double seconds = (double)(clock() - begin_time)/1000; //s
    printf("seconds:%f.\n",seconds);
    return 0;
}
`

2.

I use the following command transferring f.c file to f.wast:
`
emcc ../Examples/f.c -Os -s WASM=1 -s SIDE_MODULE=1 -o ../Examples/f.wasm
./bin/wavm-disas ../Examples/f.wasm ../Examples/f.wast
` 

3.

When I run 
`
./bin/wavm-run ../Examples/f.wast
`

4.

The following runtime exception occurs:

`
Generated stub for missing import env._clock : func ()->i32
Generated stub for missing import env._printf : func (i32, i32)->i32
Runtime exception: wavm.reachedUnreachable
Call stack:
  host!/Users/xylv/wasm/WAVM/lv/Lib/Runtime/libRuntime.dylib!WAVM::Runtime::throwException(WAVM::Runtime::ExceptionType*, std::__1::vector<WAVM::IR::UntaggedValue, std::__1::allocator<WAVM::IR::UntaggedValue> >&&)+82
  host!/Users/xylv/wasm/WAVM/lv/Lib/Runtime/libRuntime.dylib!unreachableTrap(WAVM::Runtime::ContextRuntimeData*)+39
  <unknown function>
  wasm!../Examples/f.wast!16+6
  thnk!C to WASM thunk!()->i32+0
  host!/Users/xylv/wasm/WAVM/lv/Lib/Runtime/libRuntime.dylib!WAVM::Runtime::invokeFunctionChecked(WAVM::Runtime::Context*, WAVM::Runtime::Function*, std::__1::vector<WAVM::IR::Value, std::__1::allocator<WAVM::IR::Value> > const&)+358
  host!/Users/xylv/wasm/WAVM/lv/./bin/wavm-run!main+3795

Abort trap: 6
`

Can somebody help me in solving this problem?

**Comment by AndrewScheidecker** [comment]
This is because WAVM's Emscripten ABI emulation is pretty rudimentary, and it doesn't emulate the `clock` or `printf` syscall. It used to support `printf` via some lower-level syscalls, but it looks like maybe the latest versions of Emscripten added a higher-level `printf` syscall.

If you just want to get timing information, you can remove the clock and printf calls from your C code, and enable WAVM's timing output with the WAVM_METRICS_OUTPUT cmake configuration option. When it's enabled, `wavm-run` will time the execution of your main function, and print something like this after it returns:
`Invoked function in 3.18ms`
