### ISSUE TITLE
Emscripten Threading Emulation

### ISSUE THREAD

**Issue by LukeBillo** [WAVM/WAVM#123]
Hello,

In #106 I expressed my interest in emulating emscripten threading and implementing it in Emscripten.h.

I recently had time to attempt this, and have spent a bit of time just understanding how parts of WAVM work (i.e. serialization into the IrModule, then eventually passing through to the Emscripten compartment). However, I don't quite understand how to access functions in the IrModule from within Emscripten; to my understanding, during Emscripten instantiation, the module's functions are never exposed as part of Emscripten's memory / compartment.

Not sure if I've misunderstood - am I correct in saying that the function pointer provided in `pthread_create` will be a memory offset from the base address of the functions section of the IrModule? In which case, I assume I will then have to add functions to the Emscripten instance so they can be used  within intrinsic functions? As you suggested, I was aiming to mimic what you'd achieved in ThreadTest.cpp by using the existing `Platform::Thread`.

Thanks for your time!

**Comment by AndrewScheidecker** [comment]
ThreadTest uses the reference-types extension to pass a function pointer to the syscall. The extension is not yet standardized, and so probably won't be used by Emscripten's pthread ABI for a while. ThreadTest uses the extension because it is only used to test the underlying functionality in WAVM.

The way WebAssembly generally passes function pointers around right now is as an index into a table. What you need to do is:
1. In `Emscripten::instantiate`, save the table that's created to a thread_local variable similar to `emscriptenMemory` (e.g. `emscriptenTable`).
2. In `pthread_create`, pass the saved table and the thread function index to `Runtime::getTableElement` to get the `Runtime::Function` object for the thread function.
3. In the created thread's entry function, initialize the `emscriptenMemory` and `emscriptenTable` thread_locals from the creator thread's values for those variables.
4. Call `Runtime::invokeFunctionChecked` with a new `Runtime::Context` and the `Runtime::Function` returned by `Runtime::getTableElement`.
