### ISSUE TITLE
Question: What's role of wavm-compile

### ISSUE THREAD

**Issue by mrpre** [WAVM/WAVM#168]
```
root@iZrj97ibqurmwnu9mj5htdZ:~/envoy/envoy-wasm# wavm-compile --help
Usage: wavm-compile (in.wast|in.wasm) out.wasm
```

What's the difference between `wavm-compile *wast *wasm` and `wavm-as` ?
And what's the function of `wavm-compile *wasm *wasm`  ?

**Comment by AndrewScheidecker** [comment]
`wavm-compile` produces a binary WebAssembly module that has a special section that contains the compiled object code for the module.

`wavm-run` will normally ignore this section, as to use it safely you must trust the producer of the object code. If you used `wasm-compile` to produce the .wasm file yourself, you can pass the `--precompiled` switch to `wavm-run`, and it will reuse the object code produced by `wavm-compile` instead of producing it "just in time" from the loaded WebAssembly code.

The idea is that because the compilation can take a substantial amount of time for a large module, if you are going to run a module more than once, you can use `wavm-compile` to compile it once, and `wavm-run --precompiled` to run the module without recompiling it.
