### ISSUE TITLE
WAVM Failing With "error opening input from.txt: Capabilities insufficient"

### ISSUE THREAD

**Issue by libszen** [WAVM/WAVM#238]
Hello @AndrewScheidecker - 

Latest Wavm from [here ](https://github.com/WAVM/WAVM/releases/tag/nightly%2F2019-12-04) is failing to open files using WASI ABI. 

Source code for file: [here](https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-tutorial.md#from-c) compiled with latest wasi-sdk

Verified to work on wasmtime and wasmer

WAVM CLI combinations ussed: 
`wavm run --mount-root . demo.wasm from.txt out.txt`
`wavm run --mount-root $(pwd) demo.wasm from.txt out.txt`
`wavm run --mount-root /full/path/to/dir demo.wasm from.txt out.txt`

Tried running on Windows and Linux with the same result

**Comment by AndrewScheidecker** [comment]
You need to use absolute paths, since the WASI application does not have a working directory to open paths relative to:
`wavm run --mount-root . demo.wasm /from.txt /out.txt`

This is the same in wasmtime if you use the `--mapdir=/::<path>` that is equivalent to WAVM's `--mount-root`:
`wasmtime --mapdir=/::. demo.wasm /from.txt /out.txt`

However, wasmtime additionally supports `--dir=.`, or `--mapdir=.::<path>`, and it looks like libpreopen inside the WASI libc has a special case for preopened directories named `.` to interpret it as the root for relative paths. Since WAVM only supports preopening a directory as `/`, it can't leverage that special case.

Anyway, this is not a bug, just an unintentional side effect of WAVM's different approach to filesystem sandboxing. A workaround might be for WAVM to pass the directory preopened by `--mount-root` as  both `/` and `.`.

**Comment by libszen** [comment]
Thank you for the confirmation.

**Comment by AndrewScheidecker** [comment]
> A workaround might be for WAVM to pass the directory preopened by --mount-root as both `/` and `.`.

FWIW, I implemented this workaround in cc0c8b4.
