### ISSUE TITLE
Bad import declaration causes segfault

### ISSUE THREAD

**Issue by vird** [WAVM/WAVM#261]
1. Go to Examples/embedder/cpp
2. Find and replace `getTypedInstanceExport(intrinsicsInstance, "hello1", i32_to_i32);`  to `getTypedInstanceExport(intrinsicsInstance, "hello1", i32_to_i32);`. So we make intentionally that import in WAST is not equal import we provide when calling instantiateModule
3. `make && ./embedder-example`
Expected: instantiateModule should return some error or exception
Real: instantiateModule produces `Segmentation fault (core dumped)`

**Comment by AndrewScheidecker** [comment]
The problem is because that string doesn't match the string used to name the intrinsic function here:
```
WAVM_DEFINE_INTRINSIC_FUNCTION(embedder, "hello", I32, hello, I32 argument)
{
	printf("Hello world! (argument = %i)\n", argument);
	return argument + 1;
}
```

Since it doesn't match, `getTypedInstanceExport` return `nullptr`, and passes that as an import to `instantiateModule`, which assumes that imports are non-null. It's an error in the use of the API.

I'll add a check in `instantiateModule` for null imports, just like it does some other sanity checks on the imports passed to it. It will still produce a fatal error and terminate the process, but it won't be a segfault at least.
