### ISSUE TITLE
question about multi calls of one instance

### ISSUE THREAD

**Issue by mrpre** [WAVM/WAVM#275]
I try to call a wasm function several times of an instance.  
I find each time WAVM call a wasm function by `invokeFunction` it create a `Context`.  But each time `Context` is created, it listed to a `compartment` and it's lifetime is same as it 's `compartment`, that means the num of `Context` is limited to `UINTPTR_MAX` and the memory will not be freed before `compartment` is freed.  

Is it the right way to create a new `Context` for each call ?    
If it's right, how to manage the the memory to contexts ? If I free `compartment`, the instance will also be freed which is not what I want.  
  
If not, I think it will be harmful to multi-thread because the `Context` is used to set userdata per thread.  

I'm not sure I'm in the right way to use WAVM.

**Comment by AndrewScheidecker** [comment]
You probably want to create a single `Context` and use it every time you call `invokeFunction`. If you don't want the values of WebAssembly globals to be shared between `invokeFunction` calls, then you need to create a new `Context` for each call, but that's rarely what you want.

Note that you can also use `collectCompartmentGarbage` if you are accumulating objects(`Context` or otherwise) in a compartment. Assuming they are no longer referenced, this will free their memory and IDs.

**Comment by mrpre** [comment]
perfect answer
