### ISSUE TITLE
What's needed to support microcontrollers?

### ISSUE THREAD

**Issue by beriberikix** [WAVM/WAVM#63]
My end goal is to execute wasm modules on microcontrollers like cortex m4 devices in order to develop embedded software in higher-level programming languages. The codebase looks fairly platform-agnostic. Am I correct in thinking that the main thing that's needed is to add support in `Source/Platform`? Since often times these devices are running an RTOS like FreeRTOS (which has features like threads,) one could create `freertos.cpp` and be able to target a [wide-range](https://www.freertos.org/RTOS_ports.html) of MCUs.

Does that sound feasible/correct?

**Comment by AndrewScheidecker** [comment]
Implementing the Platform abstraction layer would be necessary, but may not be sufficient:
* LLVM might be too expensive to use on embedded devices, both from a memory and speed perspective. This might be based on outdated assumptions about embedded devices, though.
* WAVM on 32-bit architectures has some known problems. When I last tried it on 32-bit ARM (Raspberry Pi), it failed to unwind exceptions through the generated code correctly. The generated code is also slower than on 64-bit architectures, since it can't reserve 4GB of memory for each WASM linear memory object and use page faults to detect out-of-bounds memory accesses.

**Comment by beriberikix** [comment]
Thanks for the reply! For the first point, I may have not been clear, but I'd expect compilation to happen on a host machine and execution of WAVM on an MCU. LLVM-based Clang definitely supports embedded targets. For the second. seeing as most MCUs have more 128KB of RAM, 4GB of reserved memory is a bigger problem :) What would be required to make memory management work on these smaller devices?

**Comment by AndrewScheidecker** [comment]
As an update on this: WAVM now has the ability to compile a WebAssembly module as part of a separate process from running it. The command to precompile the module only supports targeting the host, but it wouldn't be hard to extend that.

WAVM still has limited support for 32-bit or ARM hosts, though.

**Comment by AndrewScheidecker** [comment]
I created an issue to consolidate discussion on porting to 32-bit hosts: https://github.com/WAVM/WAVM/issues/116.

I'm closing this issue, but please feel free to open another issue if you have further questions/issues about running on embedded hosts that are not encompassed by the 32-bit issue.
