### ISSUE TITLE
VM running in 32 bit?

### ISSUE THREAD

**Issue by chrisjwein** [WAVM/WAVM#88]
Really interesting project - very nice to see a VM detached from the major JS engines.  I was wondering what you thought about running the VM in a 32 bit arch (specifically ARM but x86 as well).  64 bit is tough for IoT with typical memory constraints so looking to save there.  Presumably the sandboxing relies on a larger address space?  What if we did not run arbitrary WASM in the VM but only apps that were constrained in some way?  In an IoT app we can ensure running only signed code so true sandboxing less of a concern.

**Comment by AndrewScheidecker** [comment]
I had WAVM working on 32-bit ARM (with some caveats) in the past, but have since broken both the 32-bit and ARM support. I'd like to support ARM again, but I'm not sure about 32-bit.

The challenge with 32-bit is that it requires some different implementation trade-offs that would either need to be maintained in parallel with the 64-bit implementation, or to replace the current implementation at some performance cost on 64-bit hosts. Devices that are too small to support 64-bit addresses are also probably too small for e.g. using LLVM to JIT compile WebAssembly to native code, so I think WAVM is far from the ideal VM for such devices, and they're probably not worth supporting.

**Comment by AndrewScheidecker** [comment]
I created an issue to consolidate discussion of porting to 32-bit hosts: https://github.com/WAVM/WAVM/issues/116.
